# INFO 531 Week 16 Final Project Report

Adaria Blackwell  
INFO 531: Data Warehousing and Analytics in the Cloud  
Spring 2026  
Week 16 Final Project Report  
Dr. Nayem Rahman  
May 11, 2026


## Problem Statement

This project focuses on using machine learning to predict customer churn using the Telco Customer Churn dataset. Customer churn refers to when a customer leaves a company or stops using its services. Predicting churn is important because businesses can use this information to identify customers who may be at risk of leaving and create strategies to improve customer retention.

The goal of this project is to prepare the dataset for machine learning, identify predictor variables and the target variable, split the data into training and testing sets, and apply machine learning models to predict whether a customer will churn.

## Phase 1
### Data Source and Entities
The dataset used for this project will be a customer churn dataset obtained from Kaggle:
https://www.kaggle.com/datasets/blastchar/telco-customer-churn 

The dataset contains customer demographic information, account details, and service usage
patterns. Tentative entities include:
- Customer (CustomerID, Gender, SeniorCitizen, Partner, Dependents)
- Account (Tenure, Contract, PaperlessBilling, PaymentMethod)
- Services (PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup,
- DeviceProtection, TechSupport, StreamingTV, StreamingMovies)
- Billing (MonthlyCharges, TotalCharges)
- Churn Status (Churn)
### Tools and Technologies
The following tools and technologies will be used:
- Python (Pandas, NumPy) for data preprocessing
- Scikit-learn for machine learning model development
- Matplotlib/Seaborn for data visualization
- Jupyter Notebook for analysis and reporting
- GitHub for project documentation

## Phase 2
### Data Preparation Plan

The data preparation plan for this project involved cleaning and transforming the Telco Customer Churn dataset so it could be used for machine learning. The dataset was checked for missing values and incorrect data types. The TotalCharges column was reviewed because it loaded as a string instead of a numeric value. Categorical variables were also prepared for encoding so the machine learning models could process them.

### Predictor Variables and Target Variable

The predictor variables are the customer demographic, account, service, and billing columns that may help predict churn. Examples include tenure, Contract, InternetService, MonthlyCharges, TotalCharges, TechSupport, and PaymentMethod.

The target variable is Churn. This column shows whether a customer left the company or stayed. For machine learning, Churn will be converted into a binary variable where Yes = 1 and No = 0.

### Training and Testing Plan

The dataset will be split into training and testing sets. The training set will be used to teach the model patterns in the data, while the testing set will evaluate how well the model performs on new data. An 80/20 split will be used, meaning 80% of the data will be used for training and 20% will be used for testing.

### Machine Learning Techniques

This project will use classification models because the goal is to predict whether a customer will churn. The models used will include Logistic Regression, Decision Tree, and Random Forest.

## Phase 3
### 1.  Actual code and output generated as part of Data Preparation. Provide descriptions of this work.

In [6]:
import pandas as pd

df = pd.read_csv("data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [3]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

df["Churn"].head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

- The dataset was loaded into a Pandas dataframe to inspect the structure and contents of the data. The head() function was used to display the first five rows of the dataset to verify that the data loaded correctly. The info() function was then used to review the total number of rows, columns, and data types within the dataset. The dataset contains customer demographic, account, service, and billing information that may help predict customer churn. Next, the dataset was checked for missing values using the isnull().sum() function. The results showed that there were no missing values in the dataset. Finally, the Churn column was converted from categorical values (“Yes” and “No”) into numerical values where Yes = 1 and No = 0. This preprocessing step prepares the target variable for machine learning classification models.

 ### 2. Actual implemented code for Predictor variables or Features, and the Response or Target Variable. Provide the output generated.

In [12]:
# Predictor variables
X = df.drop("Churn", axis=1)

display(X.head())

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [13]:
# Target variable
y = df["Churn"]

display(y.head())

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

- The predictor variables were assigned to a dataframe named X by removing the Churn column from the dataset. These predictor variables include customer demographic information, account details, service usage patterns, and billing information that may help predict customer churn.

- The target variable was assigned to a variable named y using the Churn column. The output confirmed that the predictor variables and target variable were separated successfully and prepared for machine learning processing.

### 3. Actual implemented code relating to the training and testing data processing. Provide descriptions of this work. Provide the output generated and interpret the results.

In [34]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
selected_columns = [
    "gender",
    "tenure",
    "Contract",
    "InternetService",
    "PaymentMethod",
    "MonthlyCharges",
    "TotalCharges"
]

X = df[selected_columns]
y = df["Churn"]

display(X.head())
display(y.head())

,gender,tenure,Contract,InternetService,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,1,Month-to-month,DSL,Electronic check,29.85,29.85
1,Male,34,One year,DSL,Mailed check,56.95,1889.50
2,Male,2,Month-to-month,DSL,Mailed check,53.85,108.15
3,Male,45,One year,DSL,Bank transfer (automatic),42.30,1840.75
4,Female,2,Month-to-month,Fiber optic,Electronic check,70.70,151.65

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [35]:
X_encoded = pd.get_dummies(X, drop_first=True)

print("Original number of predictor columns:", X.shape[1])
print("Number of predictor columns after encoding:", X_encoded.shape[1])

display(X_encoded.head())

Original number of predictor columns: 7
Number of predictor columns after encoding: 11

,tenure,MonthlyCharges,TotalCharges,gender_Male,Contract_One year,Contract_Two year,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,29.85,29.85,False,False,False,False,False,False,True,False
1,34,56.95,1889.50,True,True,False,False,False,False,False,True
2,2,53.85,108.15,True,False,False,False,False,False,False,True
3,45,42.30,1840.75,True,True,False,False,False,False,False,False
4,2,70.70,151.65,False,False,False,True,False,False,True,False

In [36]:
from sklearn.model_selection import train_test_split
df = df.dropna()

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)

Training Features Shape: (5625, 11)
Testing Features Shape: (1407, 11)
Training Target Shape: (5625,)
Testing Target Shape: (1407,)

- The selected predictor variables were reduced to a smaller group of columns to keep the machine learning model easier to interpret and focused on important customer demographic, billing, account, and service-related information. Categorical variables such as gender, contract type, internet service type, and payment method were converted into numerical format using one-hot encoding. This preprocessing step was necessary because machine learning models cannot process text values directly.

- After encoding, the dataset increased from 7 predictor columns to 11 predictor columns. The dataset was then split into training and testing datasets using an 80/20 split with the train_test_split() function from Scikit-learn. The output showed that the training feature dataset contained 5,634 rows and 11 columns, while the testing feature dataset contained 1,409 rows and 11 columns. The training target dataset contained 5,634 rows, and the testing target dataset contained 1,409 rows.

### 4. Provide the step-by-step code for each ML technique(s). Provide the output generated and interpret the results.

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [40]:
log_model = LogisticRegression(max_iter=5000, solver="liblinear")

log_model.fit(X_train, y_train)

log_predictions = log_model.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, log_predictions))
print(classification_report(y_test, log_predictions))

Logistic Regression Accuracy: 0.7910447761194029
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.63      0.51      0.56       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

- The Logistic Regression model achieved an accuracy of approximately 79%. This means the model correctly predicted customer churn status for about 79% of the testing records.The model performed better at predicting customers who did not churn, shown by the higher precision, recall, and F1-score for class 0. The results for class 1, which represents customers who churned, were lower. This shows that predicting churned customers is more difficult, but the model still provides useful insight into customer churn patterns.

In [41]:
tree_model = DecisionTreeClassifier(random_state=42)

tree_model.fit(X_train, y_train)

tree_predictions = tree_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, tree_predictions))
print(classification_report(y_test, tree_predictions))

Decision Tree Accuracy: 0.7320540156361052
              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1033
           1       0.50      0.47      0.48       374

    accuracy                           0.73      1407
   macro avg       0.65      0.65      0.65      1407
weighted avg       0.73      0.73      0.73      1407

- The Decision Tree model achieved an accuracy of approximately 73%. This means the model correctly predicted customer churn status for about 73% of the customers in the testing dataset. The results showed that the model performed better at identifying customers who stayed with the company than customers who churned. This can be seen through the higher precision, recall, and F1-score values for class 0 (non-churn customers). The lower scores for class 1 indicate that predicting churned customers is more difficult because customer behavior patterns can vary. Overall, the Decision Tree model demonstrated that customer contract type, billing information, and internet services can help identify customer churn patterns.

In [42]:
forest_model = RandomForestClassifier(random_state=42)

forest_model.fit(X_train, y_train)

forest_predictions = forest_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, forest_predictions))
print(classification_report(y_test, forest_predictions))

Random Forest Accuracy: 0.7540867093105899
              precision    recall  f1-score   support

           0       0.81      0.87      0.84      1033
           1       0.55      0.44      0.49       374

    accuracy                           0.75      1407
   macro avg       0.68      0.65      0.66      1407
weighted avg       0.74      0.75      0.75      1407

- The Random Forest model achieved an accuracy of approximately 75%. This means the model correctly predicted customer churn status for about 75% of the customers in the testing dataset.The results showed that the Random Forest model performed slightly better than the Decision Tree model. Similar to the other models, the Random Forest model predicted customers who stayed with the company more accurately than customers who churned. This is shown by the higher precision, recall, and F1-score values for class 0. Overall, the Random Forest model demonstrated that customer demographics, account details, internet service type, and billing information all contribute to predicting customer churn behavior.

## Summary
#### This project focused on using machine learning techniques to predict customer churn using the Telco Customer Churn dataset from Kaggle. The project included multiple stages such as data preparation, identifying predictor and target variables, preprocessing categorical data, splitting the dataset into training and testing sets, and applying machine learning models. Python libraries such as Pandas and Scikit-learn were used throughout the project to prepare and analyze the dataset.

#### Three machine learning models were implemented during this project: Logistic Regression, Decision Tree, and Random Forest. The results showed that the Logistic Regression model produced the highest accuracy at approximately 79%, followed by the Random Forest model at approximately 75%, and the Decision Tree model at approximately 73%. Overall, the project demonstrated how machine learning can be used to identify patterns in customer behavior and help businesses predict which customers may be at risk of leaving a company.